### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Jelle-S** [BartDelrue/allieTabs#19]
When version 1.2.5 is downloaded through npm/yarn, the /dist/allieTabs.js and /dist/allieTabs.min.js file contain the following line:
```
 var _Object$defineProperty = require("@babel/runtime-corejs2/core-js/object/define-property");
```
which causes
```
Uncaught ReferenceError: require is not defined <anonymous> [..]/allieTabs.js allieTabs.js
```

Which is weird, because the dist files hosted on github do not contain this line. Could you create a new release, or republish 1.2.5 to npm so this issue gets fixed please?

**Comment by BartDelrue** [comment]
Sure, I'll have a look and see if I can create a patch to help you out.

If this is still in active use, it might be time for a bigger rewrite... I'll keep you posted.

**Comment by BartDelrue** [comment]
@Jelle-S 
For now, please try 1.2.6

It will probably not work in IE anymore, I removed a lot of legacy babel plugins. 
But IE is dead anyway...

Additionally I see no reason not to use the es6 version from now on.
I might remove UMD support in total if there's a need for a new major version.
