### ISSUE TITLE
Can't use with `ol[role="tablist"]`

### ISSUE THREAD

**Issue by sntran** [BartDelrue/allieTabs#8]
The query at https://github.com/BartDelrue/allieTabs/blob/731837c26ca9e348cbdaf2b5e951aafbf2b0b2db/src/allieTabs.js#L102 prevents us to use `<ol>` as the tablist.

Please remove the `ol` from your selector.
Also, please consider remove `li[role="presentation"]` from the query selector for the tabs. `[role="tab"]` should be enough.

**Comment by BartDelrue** [comment]
Hi sntran,

Thank you for bringing this to my attention.
I'm currently on holiday without access to a computer, I'll have a look at this in the beginning of August.

Feel free to create a pull request though.

Just keep in mind that the current selectors will likely have been copied in people's CSS files, I know I do for some projects.
I don't want to create breaking changes.

As for `li[role=presentation]`, I'd have to check some sources and do some testing with screen readers. This code is quite old, but I believe I followed instructions from webAIM and/or Heydon Pickering.

**Comment by sntran** [comment]
Hi Bart!

Thanks for being open about PR. I have submitted one.

The users' CSS selector can remain the same, as the new proposed selector is a subset of that.

I understand the `li[role="presentation"]`, but that is on the markup, not your JS. And a element with `role="tab"` does not need to be a `<a>` either.

**Comment by BartDelrue** [comment]
Thanks again sntran.
I've released 1.2.4.
